FROM node:20-alpine AS builder

WORKDIR /app

COPY web-admin/package*.json ./
RUN npm install

COPY web-admin ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY infrastructure/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

